# Can CPL_VSIL_CURL_ALLOWED_EXTENSIONS be switched on and off at run time (scoped use)?
Sys.setenv(RWAPOR_AUTO_CONFIG = "false", CPL_CURL_VERBOSE = "YES", GDAL_DISABLE_READDIR_ON_OPEN = "EMPTY_DIR")
pj <- system.file("proj", package = "sf"); Sys.setenv(PROJ_LIB = pj, PROJ_DATA = pj)
suppressMessages(pkgload::load_all(".", quiet = TRUE))
u <- paste0("/vsicurl/", sub("^/vsicurl/", "", wapor_generate_urls("L3-AETI-D", l3_region = "JVA", period = c("2023-01-01", "2023-02-28"))))
read_one <- function(i) invisible(terra::global(terra::rast(u[i]), "mean", na.rm = TRUE))
message("MARK 1 no filter"); read_one(1)
terra::setGDALconfig("CPL_VSIL_CURL_ALLOWED_EXTENSIONS", ".tif,.tiff")
message("MARK 2 filter set at run time"); read_one(2)
terra::setGDALconfig("CPL_VSIL_CURL_ALLOWED_EXTENSIONS", "")
message("MARK 3 filter cleared"); read_one(3)
terra::setGDALconfig("CPL_VSIL_CURL_ALLOWED_EXTENSIONS", ".tif,.tiff")
message("MARK 4 filter set again"); read_one(4)
up <- gsub("tif$", "TIF", u[5])
ok <- tryCatch({ terra::rast(up); "opened" }, error = function(e) "refused")
message("MARK 5 upper-case TIF with filter: ", ok)
