a <- commandArgs(trailingOnly = TRUE)
Sys.setenv(RWAPOR_AUTO_CONFIG = a[1])
tm <- function(e) { t0 <- proc.time()[["elapsed"]]; force(e); round(proc.time()[["elapsed"]] - t0, 2) }
suppressMessages(pkgload::load_all(".", quiet = TRUE)); options(Rwapor.verbose = FALSE)
cat("auto config:", a[1], "| PROJ_LIB:", Sys.getenv("PROJ_LIB"), "\n")
urls <- sub("^/vsicurl/", "", wapor_generate_urls("L3-AETI-D", l3_region = "JVA", period = c("2023-01-01", "2023-12-31")))
dir <- file.path(tempdir(), "l3c"); dir.create(dir, showWarnings = FALSE)
dest <- file.path(dir, basename(urls)); invisible(curl::multi_download(urls, dest, progress = FALSE))
cat("rast(1 file):", tm(r1 <- terra::rast(dest[1])), "s | again:", tm(r1 <- terra::rast(dest[2])), "s\n")
cat("rast(36 files) one call:", tm(r <- terra::rast(dest)), "s\n")
cat("36 x rast(file) separately:", tm(l <- lapply(dest, terra::rast)), "s\n")
cat("rast(list of 36):", tm(r2 <- terra::rast(l)), "s\n")
cat("values of all 36 layers:", tm(v <- terra::values(r)), "s\n")
cat("gdal describe 36 (no terra object):", tm(for (f in dest) terra::describe(f)), "s\n")
cat("sf::gdal_utils info 36:", tm(for (f in dest) sf::gdal_utils("info", f, quiet = TRUE)), "s\n")
m <- file.path(dir, "stack.tif"); terra::writeRaster(r, m, overwrite = TRUE)
cat("rast(one 36-band file):", tm(rm1 <- terra::rast(m)), "s | values:", tm(v <- terra::values(rm1)), "s\n")
